name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install PyInstaller
        run: pip install pyinstaller

      # Step 4: Build the Python script to EXE
      - name: Build EXE
        run: pyinstaller --onefile your_script.py

      # Step 5: Upload the generated EXE as an artifact
      - name: Upload EXE
        uses: actions/upload-artifact@v3
        with:
          name: built-exe
          path: dist/your_script.exe